name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.0.11
  - seaborn=0.12.2
  - pandas=2.0.3
  - pip=23.3.2
  - ydata-profiling=4.6.4
  - pyarrow=14.0.2
  - pydantic-settings=2.1.0
  - ipywidgets=8.1.1
  - pip:
      - wandb==0.16.2