name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.31.0
  - pip=23.3.2
  - seaborn=0.13.1
  - pandas=2.0.3
  - scikit-learn=1.3.2
  - matplotlib==3.7.3
  - pillow=10.2.0
  - pip:
      - wandb==0.16.2